;              
CREATE USER IF NOT EXISTS "SA" SALT '7762ef8186211312' HASH '3d7ddffce75f4fdf3b15468d84f441b8e2d27afeb55fb6704fca27fb921b081e' ADMIN;          
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_F9628AFA_429A_4A07_A7EA_4DD5E97A39B8" START WITH 1 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_49406B91_52FA_4EBD_9655_54A075F9531D" START WITH 3 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_353052D0_AFD2_47AF_926F_44C5500A4BEC" START WITH 2 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."HIBERNATE_SEQUENCE" START WITH 2;    
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_3010B16A_CA6C_4440_AC0B_76596B1CBBE4" START WITH 2 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_B454ABDB_C07E_4714_A28E_2E7DD7EF38D8" START WITH 1 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_D96801DE_CDE7_4A1F_B26A_CFAE5800918A" START WITH 1 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_9C747EB2_E7D0_4C8B_A78C_65CCC5C2D7AF" START WITH 1 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_EB83CA99_CC76_49A9_8938_7000F11E081B" START WITH 2 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_C9A51CDF_6E92_4E3F_A1B2_23270DDE7EA4" START WITH 1 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_95C5DEE5_C17B_41A3_A853_84D3BAE7093C" START WITH 3 BELONGS_TO_TABLE; 
CREATE MEMORY TABLE "PUBLIC"."CHAT"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_9C747EB2_E7D0_4C8B_A78C_65CCC5C2D7AF") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_9C747EB2_E7D0_4C8B_A78C_65CCC5C2D7AF",
    "CONTENT" TEXT,
    "RECEIVER" BIGINT NOT NULL,
    "SEND_AT" TIMESTAMP,
    "SENDER" BIGINT NOT NULL,
    "VUE" BOOLEAN NOT NULL
);      
ALTER TABLE "PUBLIC"."CHAT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CHAT;     
CREATE MEMORY TABLE "PUBLIC"."COMMENT"(
    "ID" BIGINT NOT NULL,
    "CONTENT" VARCHAR(255),
    "CREATED_AT" TIMESTAMP,
    "ID_REPLAY" BIGINT NOT NULL,
    "PARENT_ID" BIGINT NOT NULL,
    "USER_ID" BIGINT NOT NULL
);   
ALTER TABLE "PUBLIC"."COMMENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("ID");       
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.COMMENT;  
INSERT INTO "PUBLIC"."COMMENT" VALUES
(1, 'Did you like this tutorial?', TIMESTAMP '2022-02-15 17:16:07.546', 0, 1, 2);        
CREATE MEMORY TABLE "PUBLIC"."FIELD"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_353052D0_AFD2_47AF_926F_44C5500A4BEC") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_353052D0_AFD2_47AF_926F_44C5500A4BEC",
    "DESCR" VARCHAR(255),
    "IS_ARRCHIVED" BOOLEAN NOT NULL,
    "NAME" VARCHAR(255)
);    
ALTER TABLE "PUBLIC"."FIELD" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID");         
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.FIELD;    
INSERT INTO "PUBLIC"."FIELD" VALUES
(1, 'Programming Languages', FALSE, 'Programming Languages');              
CREATE MEMORY TABLE "PUBLIC"."GROUPE"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_F9628AFA_429A_4A07_A7EA_4DD5E97A39B8") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_F9628AFA_429A_4A07_A7EA_4DD5E97A39B8",
    "ACCEPTED_USERS" VARCHAR(255),
    "NAME" VARCHAR(255),
    "NBR_USERS" INTEGER NOT NULL,
    "OWNER" BIGINT NOT NULL,
    "STATE" INTEGER NOT NULL,
    "USERS" VARCHAR(255)
);        
ALTER TABLE "PUBLIC"."GROUPE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID");        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.GROUPE;   
CREATE MEMORY TABLE "PUBLIC"."LEARNING_EVENT"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_3010B16A_CA6C_4440_AC0B_76596B1CBBE4") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_3010B16A_CA6C_4440_AC0B_76596B1CBBE4",
    "ALLOWED_GROUPES" VARCHAR(255),
    "CONTENT" TEXT,
    "CONTENT_TYPE" INTEGER NOT NULL,
    "TITLE" VARCHAR(255),
    "SUBJECT_ID" BIGINT NOT NULL,
    "TEACHER_ID" BIGINT NOT NULL
);        
ALTER TABLE "PUBLIC"."LEARNING_EVENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("ID");
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.LEARNING_EVENT;           
INSERT INTO "PUBLIC"."LEARNING_EVENT" VALUES
(1, '', '<h2>What is Java?</h2><p><strong>Java</strong> is a general-purpose, class-based, object-oriented programming language designed for having lesser implementation dependencies. It is a computing platform for application development. Java is fast, secure, and reliable, therefore. It is widely used for developing Java applications in laptops, data centers, game consoles, scientific supercomputers, cell phones, etc.</p><h2>What is Java Platform?</h2><p><strong>Java Platform</strong> is a collection of programs that help programmers to develop and run Java programming applications efficiently. It includes an execution engine, a compiler, and a set of libraries in it. It is a set of computer software and specifications. James Gosling developed the Java platform at Sun Microsystems, and the Oracle Corporation later acquired it.</p>', 1, 'What is Java? ', 1, 2);        
CREATE MEMORY TABLE "PUBLIC"."PERSON"(
    "ID_USER" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_95C5DEE5_C17B_41A3_A853_84D3BAE7093C") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_95C5DEE5_C17B_41A3_A853_84D3BAE7093C",
    "BLOCK_DATE" TIMESTAMP,
    "CONFIRM_PASSWORD" VARCHAR(255),
    "EMAIL" VARCHAR(255),
    "LAST_VISIT_DATE" TIMESTAMP,
    "NBR_ADDED" INTEGER NOT NULL,
    "PASSWORD" VARCHAR(255),
    "TYPE" INTEGER NOT NULL,
    "USER_STATE" INTEGER NOT NULL,
    "USERNAME" VARCHAR(255)
);              
ALTER TABLE "PUBLIC"."PERSON" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID_USER");   
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.PERSON;   
INSERT INTO "PUBLIC"."PERSON" VALUES
(1, NULL, '', 'salim.kham@yandex.ru', NULL, 0, '$2a$10$/F6ouKKdUUAcFkv8dQ.3gugNtKrP.O4WcvEPVInuaV.vME5L8/Heu', 1, 1, 'admin'),
(2, NULL, '', 'salim.kham1991@mail.ru', NULL, 0, '$2a$10$r7RJkQa4/iJ.1DbFafioeemLgMuMRdl71qgxd7aMexzT3lP90mV66', 3, 1, 'salim');           
CREATE MEMORY TABLE "PUBLIC"."QUESTION"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_D96801DE_CDE7_4A1F_B26A_CFAE5800918A") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_D96801DE_CDE7_4A1F_B26A_CFAE5800918A",
    "QUESTION" TEXT,
    "MARK" INTEGER NOT NULL,
    "QUESTIONNNARY_ID" BIGINT NOT NULL
);               
ALTER TABLE "PUBLIC"."QUESTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.QUESTION; 
CREATE MEMORY TABLE "PUBLIC"."QUESTIONNARY"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_B454ABDB_C07E_4714_A28E_2E7DD7EF38D8") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_B454ABDB_C07E_4714_A28E_2E7DD7EF38D8",
    "ID_TUTORIAL" BIGINT
);           
ALTER TABLE "PUBLIC"."QUESTIONNARY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7F" PRIMARY KEY("ID"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.QUESTIONNARY;             
CREATE MEMORY TABLE "PUBLIC"."RESPONSE"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_C9A51CDF_6E92_4E3F_A1B2_23270DDE7EA4") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_C9A51CDF_6E92_4E3F_A1B2_23270DDE7EA4",
    "CONTENT" TEXT,
    "RESPONSE_ORDER" INTEGER NOT NULL,
    "VALIDE" BOOLEAN NOT NULL,
    "QUESTION_ID" BIGINT NOT NULL
);            
ALTER TABLE "PUBLIC"."RESPONSE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1A" PRIMARY KEY("ID");     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RESPONSE; 
CREATE MEMORY TABLE "PUBLIC"."SUBJECT"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_EB83CA99_CC76_49A9_8938_7000F11E081B") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_EB83CA99_CC76_49A9_8938_7000F11E081B",
    "DESCRIPTION" VARCHAR(255),
    "NAME" VARCHAR(255),
    "FIELD_ID" BIGINT NOT NULL
); 
ALTER TABLE "PUBLIC"."SUBJECT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("ID");       
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.SUBJECT;  
INSERT INTO "PUBLIC"."SUBJECT" VALUES
(1, NULL, 'JAVA', 1);    
CREATE MEMORY TABLE "PUBLIC"."TEACHER"(
    "CV" VARCHAR(255),
    "JOINED_GROUPES" VARCHAR(255),
    "ID_USER" BIGINT NOT NULL
);             
ALTER TABLE "PUBLIC"."TEACHER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("ID_USER");  
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.TEACHER;  
INSERT INTO "PUBLIC"."TEACHER" VALUES
(NULL, '', 1),
(NULL, '', 2);            
CREATE MEMORY TABLE "PUBLIC"."TUTORIAL"(
    "CREATE_AT" TIMESTAMP,
    "DELAY_COMMENT" INTEGER NOT NULL,
    "NBR_COMMENT" INTEGER NOT NULL,
    "NBR_VISITOR" INTEGER NOT NULL,
    "ID" BIGINT NOT NULL
);  
ALTER TABLE "PUBLIC"."TUTORIAL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3A" PRIMARY KEY("ID");     
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.TUTORIAL; 
INSERT INTO "PUBLIC"."TUTORIAL" VALUES
(TIMESTAMP '2022-02-15 17:12:09.879', 50, 1, 2, 1);     
CREATE MEMORY TABLE "PUBLIC"."USER_INFO"(
    "ID_INFO" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_49406B91_52FA_4EBD_9655_54A075F9531D") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_49406B91_52FA_4EBD_9655_54A075F9531D",
    "ADDRESS" VARCHAR(255),
    "BIRTHDAY" TIMESTAMP,
    "BIRTHDAY_TYPE" INTEGER NOT NULL,
    "FIRST_NAME" VARCHAR(255),
    "LAST_NAME" VARCHAR(255),
    "PHOTO" VARCHAR(255),
    "RAND" INTEGER NOT NULL,
    "SEX" CHAR(255) NOT NULL,
    "ID_USER" BIGINT
);               
ALTER TABLE "PUBLIC"."USER_INFO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_BC" PRIMARY KEY("ID_INFO");               
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.USER_INFO;
INSERT INTO "PUBLIC"."USER_INFO" VALUES
(1, NULL, NULL, 0, NULL, NULL, 'https://www.dropbox.com/s/aho4avlx6jfrsg3/profileimage12.png?raw=1& https://www.dropbox.com/s/0kt087envcyuned/profileimage1.png?raw=1&', 20, STRINGDECODE('\u0000'), 1),
(2, 'Algeria', NULL, 0, 'salim', 'kham', 'https://i.pravatar.cc/50?img=27 https://i.pravatar.cc/50?img=27', 27, STRINGDECODE('\u0000'), 2);   
ALTER TABLE "PUBLIC"."USER_INFO" ADD CONSTRAINT "PUBLIC"."UK_MNHQYIHJJFYDARCG6YY2LPOYA" UNIQUE("ID_USER");     
ALTER TABLE "PUBLIC"."QUESTIONNARY" ADD CONSTRAINT "PUBLIC"."UK_G8RMSVLN6AVG84D7I1AABBURY" UNIQUE("ID_TUTORIAL");              
ALTER TABLE "PUBLIC"."PERSON" ADD CONSTRAINT "PUBLIC"."UK_N0I6D7RC1HQKJIVK494G8J2QD" UNIQUE("USERNAME");       
ALTER TABLE "PUBLIC"."PERSON" ADD CONSTRAINT "PUBLIC"."UK_FWMWI44U55BO4RVWSV0CLN012" UNIQUE("EMAIL");          
ALTER TABLE "PUBLIC"."GROUPE" ADD CONSTRAINT "PUBLIC"."UK_3GDPPNYWPDR0JQBRJDDP810BR" UNIQUE("NAME");           
ALTER TABLE "PUBLIC"."FIELD" ADD CONSTRAINT "PUBLIC"."UK_HXX23XWP6CXWM1UAX4DODI1AV" UNIQUE("NAME");            
ALTER TABLE "PUBLIC"."QUESTIONNARY" ADD CONSTRAINT "PUBLIC"."FK8CMIN1NJ5M4K0JA8PFEHBSXOB" FOREIGN KEY("ID_TUTORIAL") REFERENCES "PUBLIC"."TUTORIAL"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."RESPONSE" ADD CONSTRAINT "PUBLIC"."FK3E7ADCO6SQ6ONRICR8S3GLU62" FOREIGN KEY("QUESTION_ID") REFERENCES "PUBLIC"."QUESTION"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."TUTORIAL" ADD CONSTRAINT "PUBLIC"."FK3TFRFITS7ED2IDHW7D1D3VH0N" FOREIGN KEY("ID") REFERENCES "PUBLIC"."LEARNING_EVENT"("ID") NOCHECK;    
ALTER TABLE "PUBLIC"."TEACHER" ADD CONSTRAINT "PUBLIC"."FK1XIKJO49S2B0PT45RXUVD1AXT" FOREIGN KEY("ID_USER") REFERENCES "PUBLIC"."PERSON"("ID_USER") NOCHECK;   
ALTER TABLE "PUBLIC"."LEARNING_EVENT" ADD CONSTRAINT "PUBLIC"."FK1SY57CP8JX9XP7C2XGA1FOT4L" FOREIGN KEY("TEACHER_ID") REFERENCES "PUBLIC"."TEACHER"("ID_USER") NOCHECK;        
ALTER TABLE "PUBLIC"."SUBJECT" ADD CONSTRAINT "PUBLIC"."FK33W7AIGIWM8R31IUGDVBGECM7" FOREIGN KEY("FIELD_ID") REFERENCES "PUBLIC"."FIELD"("ID") NOCHECK;        
ALTER TABLE "PUBLIC"."USER_INFO" ADD CONSTRAINT "PUBLIC"."FK9CRS2QP3HFKM140KEX944JLET" FOREIGN KEY("ID_USER") REFERENCES "PUBLIC"."PERSON"("ID_USER") NOCHECK; 
ALTER TABLE "PUBLIC"."QUESTION" ADD CONSTRAINT "PUBLIC"."FK49CRTL3LBARPRQH9D3W10OJOW" FOREIGN KEY("QUESTIONNNARY_ID") REFERENCES "PUBLIC"."QUESTIONNARY"("ID") NOCHECK;        
ALTER TABLE "PUBLIC"."COMMENT" ADD CONSTRAINT "PUBLIC"."FKJY4M3PLKOPIJ1M8B1O9H3LRE0" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."PERSON"("ID_USER") NOCHECK;   
ALTER TABLE "PUBLIC"."LEARNING_EVENT" ADD CONSTRAINT "PUBLIC"."FK1GQUOA7SYEKHR2WJ516IATROW" FOREIGN KEY("SUBJECT_ID") REFERENCES "PUBLIC"."SUBJECT"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."COMMENT" ADD CONSTRAINT "PUBLIC"."FKFVWM0MY5SLXXLHQQGY94LGXI1" FOREIGN KEY("PARENT_ID") REFERENCES "PUBLIC"."LEARNING_EVENT"("ID") NOCHECK;              
