;              
CREATE USER IF NOT EXISTS "SA" SALT '5ce7fa79049c7960' HASH '93c8ba5d7e76ff332e4bb768faedba2eafcf6751ae299dd7ba17f5ecc4ea8bf2' ADMIN;          
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_070A271B_2DF8_4B90_9B52_6CCD0742B764" START WITH 2 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_F498F7AB_B657_4FCD_9AD0_0184D79B8A40" START WITH 1 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_D3CD7187_5CE8_4FA3_B477_E9CB292EA5A1" START WITH 1 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."HIBERNATE_SEQUENCE" START WITH 1;    
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_231B4F3B_8279_4497_B60B_FCA1A6E40F3E" START WITH 1 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_DE12A2B1_3B07_4AA4_9EBC_BB704EC2E18E" START WITH 1 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_CCF2ECBD_3A9D_4466_A886_0FFE2260E960" START WITH 1 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_9DAD811F_1B8B_467E_969B_F1E6E7A303A1" START WITH 2 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_0A37D05A_31A6_4AE8_8F0E_F215DD515922" START WITH 1 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_8B16CC15_E7D7_46E9_8C65_98325D369CF7" START WITH 1 BELONGS_TO_TABLE; 
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_AD1CFE55_22BC_4EDB_9B18_40E1673AB22F" START WITH 1 BELONGS_TO_TABLE; 
CREATE MEMORY TABLE "PUBLIC"."CHAT"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_8B16CC15_E7D7_46E9_8C65_98325D369CF7") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_8B16CC15_E7D7_46E9_8C65_98325D369CF7",
    "CONTENT" TEXT,
    "RECEIVER" BIGINT NOT NULL,
    "SEND_AT" TIMESTAMP,
    "SENDER" BIGINT NOT NULL,
    "VUE" BOOLEAN NOT NULL
);      
ALTER TABLE "PUBLIC"."CHAT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CHAT;     
CREATE MEMORY TABLE "PUBLIC"."COMMENT"(
    "ID" BIGINT NOT NULL,
    "CONTENT" VARCHAR(255),
    "CREATED_AT" TIMESTAMP,
    "ID_REPLAY" BIGINT NOT NULL,
    "PARENT_ID" BIGINT NOT NULL,
    "USER_ID" BIGINT NOT NULL
);   
ALTER TABLE "PUBLIC"."COMMENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("ID");       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.COMMENT;  
CREATE MEMORY TABLE "PUBLIC"."FIELD"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_DE12A2B1_3B07_4AA4_9EBC_BB704EC2E18E") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_DE12A2B1_3B07_4AA4_9EBC_BB704EC2E18E",
    "DESCR" VARCHAR(255),
    "IS_ARRCHIVED" BOOLEAN NOT NULL,
    "NAME" VARCHAR(255)
);    
ALTER TABLE "PUBLIC"."FIELD" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID");         
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.FIELD;    
CREATE MEMORY TABLE "PUBLIC"."GROUPE"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_0A37D05A_31A6_4AE8_8F0E_F215DD515922") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_0A37D05A_31A6_4AE8_8F0E_F215DD515922",
    "ACCEPTED_STUDENTS" VARCHAR(255),
    "NAME" VARCHAR(255),
    "NBR_USERS" INTEGER NOT NULL,
    "STATE" INTEGER NOT NULL,
    "OWNER_ID" BIGINT NOT NULL
);            
ALTER TABLE "PUBLIC"."GROUPE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID");        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.GROUPE;   
CREATE MEMORY TABLE "PUBLIC"."GROUPE_EVENT"(
    "EVENT_ID" BIGINT NOT NULL,
    "GROUPE_ID" BIGINT NOT NULL
);
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.GROUPE_EVENT;             
CREATE MEMORY TABLE "PUBLIC"."GROUPE_STUDENT"(
    "GROUPE_ID" BIGINT NOT NULL,
    "STUDENT_ID" BIGINT NOT NULL
);            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.GROUPE_STUDENT;           
CREATE MEMORY TABLE "PUBLIC"."LEARNING_EVENT"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_F498F7AB_B657_4FCD_9AD0_0184D79B8A40") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_F498F7AB_B657_4FCD_9AD0_0184D79B8A40",
    "CONTENT" TEXT,
    "CONTENT_TYPE" INTEGER NOT NULL,
    "TITLE" VARCHAR(255),
    "SUBJECT_ID" BIGINT NOT NULL,
    "TEACHER_ID" BIGINT NOT NULL
);            
ALTER TABLE "PUBLIC"."LEARNING_EVENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.LEARNING_EVENT;           
CREATE MEMORY TABLE "PUBLIC"."PERSON"(
    "ID_USER" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_9DAD811F_1B8B_467E_969B_F1E6E7A303A1") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_9DAD811F_1B8B_467E_969B_F1E6E7A303A1",
    "BLOCK_DATE" TIMESTAMP,
    "CONFIRM_PASSWORD" VARCHAR(255),
    "EMAIL" VARCHAR(255),
    "LAST_VISIT_DATE" TIMESTAMP,
    "NBR_ADDED" INTEGER NOT NULL,
    "PASSWORD" VARCHAR(255),
    "TYPE" INTEGER NOT NULL,
    "USER_STATE" INTEGER NOT NULL,
    "USERNAME" VARCHAR(255)
);              
ALTER TABLE "PUBLIC"."PERSON" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID_USER");   
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.PERSON;   
INSERT INTO "PUBLIC"."PERSON" VALUES
(1, NULL, '', 'salim.kham@yandex.ru', NULL, 0, '$2a$10$zrVU7Uv0dgLOYcRnCBDg2uhpQZJBrbuqY9/nT7D.bpvaMf.PLSWvK', 1, 1, 'admin');            
CREATE MEMORY TABLE "PUBLIC"."QUESTION"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_231B4F3B_8279_4497_B60B_FCA1A6E40F3E") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_231B4F3B_8279_4497_B60B_FCA1A6E40F3E",
    "QUESTION" TEXT,
    "MARK" INTEGER NOT NULL,
    "QUESTIONNNARY_ID" BIGINT NOT NULL
);               
ALTER TABLE "PUBLIC"."QUESTION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.QUESTION; 
CREATE MEMORY TABLE "PUBLIC"."QUESTIONNARY"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_D3CD7187_5CE8_4FA3_B477_E9CB292EA5A1") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_D3CD7187_5CE8_4FA3_B477_E9CB292EA5A1",
    "ID_TUTORIAL" BIGINT
);           
ALTER TABLE "PUBLIC"."QUESTIONNARY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7F" PRIMARY KEY("ID"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.QUESTIONNARY;             
CREATE MEMORY TABLE "PUBLIC"."RESPONSE"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_AD1CFE55_22BC_4EDB_9B18_40E1673AB22F") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_AD1CFE55_22BC_4EDB_9B18_40E1673AB22F",
    "CONTENT" TEXT,
    "RESPONSE_ORDER" INTEGER NOT NULL,
    "VALIDE" BOOLEAN NOT NULL,
    "QUESTION_ID" BIGINT NOT NULL
);            
ALTER TABLE "PUBLIC"."RESPONSE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1A" PRIMARY KEY("ID");     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RESPONSE; 
CREATE MEMORY TABLE "PUBLIC"."STUDENT"(
    "ID_USER" BIGINT NOT NULL
);       
ALTER TABLE "PUBLIC"."STUDENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("ID_USER");  
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.STUDENT;  
CREATE MEMORY TABLE "PUBLIC"."SUBJECT"(
    "ID" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_CCF2ECBD_3A9D_4466_A886_0FFE2260E960") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_CCF2ECBD_3A9D_4466_A886_0FFE2260E960",
    "DESCRIPTION" VARCHAR(255),
    "NAME" VARCHAR(255),
    "FIELD_ID" BIGINT NOT NULL
); 
ALTER TABLE "PUBLIC"."SUBJECT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_BB" PRIMARY KEY("ID");      
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.SUBJECT;  
CREATE MEMORY TABLE "PUBLIC"."TEACHER"(
    "CV" VARCHAR(255),
    "ID_USER" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."TEACHER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("ID_USER");  
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.TEACHER;  
INSERT INTO "PUBLIC"."TEACHER" VALUES
(NULL, 1);               
CREATE MEMORY TABLE "PUBLIC"."TUTORIAL"(
    "CREATE_AT" TIMESTAMP,
    "DELAY_COMMENT" INTEGER NOT NULL,
    "NBR_COMMENT" INTEGER NOT NULL,
    "NBR_VISITOR" INTEGER NOT NULL,
    "ID" BIGINT NOT NULL
);  
ALTER TABLE "PUBLIC"."TUTORIAL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3A" PRIMARY KEY("ID");     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TUTORIAL; 
CREATE MEMORY TABLE "PUBLIC"."USER_INFO"(
    "ID_INFO" BIGINT DEFAULT (NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_070A271B_2DF8_4B90_9B52_6CCD0742B764") NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_070A271B_2DF8_4B90_9B52_6CCD0742B764",
    "ADDRESS" VARCHAR(255),
    "BIRTHDAY" TIMESTAMP,
    "BIRTHDAY_TYPE" INTEGER NOT NULL,
    "FIRST_NAME" VARCHAR(255),
    "LAST_NAME" VARCHAR(255),
    "PHOTO" VARCHAR(255),
    "RAND" INTEGER NOT NULL,
    "SEX" CHAR(255) NOT NULL,
    "ID_USER" BIGINT
);               
ALTER TABLE "PUBLIC"."USER_INFO" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_BC" PRIMARY KEY("ID_INFO");               
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.USER_INFO;
INSERT INTO "PUBLIC"."USER_INFO" VALUES
(1, NULL, NULL, 0, NULL, NULL, 'https://i.pravatar.cc/50?img=82 https://i.pravatar.cc/50?img=82', 82, STRINGDECODE('\u0000'), 1);      
ALTER TABLE "PUBLIC"."USER_INFO" ADD CONSTRAINT "PUBLIC"."UK_MNHQYIHJJFYDARCG6YY2LPOYA" UNIQUE("ID_USER");     
ALTER TABLE "PUBLIC"."QUESTIONNARY" ADD CONSTRAINT "PUBLIC"."UK_G8RMSVLN6AVG84D7I1AABBURY" UNIQUE("ID_TUTORIAL");              
ALTER TABLE "PUBLIC"."PERSON" ADD CONSTRAINT "PUBLIC"."UK_N0I6D7RC1HQKJIVK494G8J2QD" UNIQUE("USERNAME");       
ALTER TABLE "PUBLIC"."PERSON" ADD CONSTRAINT "PUBLIC"."UK_FWMWI44U55BO4RVWSV0CLN012" UNIQUE("EMAIL");          
ALTER TABLE "PUBLIC"."GROUPE" ADD CONSTRAINT "PUBLIC"."UK_3GDPPNYWPDR0JQBRJDDP810BR" UNIQUE("NAME");           
ALTER TABLE "PUBLIC"."FIELD" ADD CONSTRAINT "PUBLIC"."UK_HXX23XWP6CXWM1UAX4DODI1AV" UNIQUE("NAME");            
ALTER TABLE "PUBLIC"."QUESTIONNARY" ADD CONSTRAINT "PUBLIC"."FK8CMIN1NJ5M4K0JA8PFEHBSXOB" FOREIGN KEY("ID_TUTORIAL") REFERENCES "PUBLIC"."TUTORIAL"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."RESPONSE" ADD CONSTRAINT "PUBLIC"."FK3E7ADCO6SQ6ONRICR8S3GLU62" FOREIGN KEY("QUESTION_ID") REFERENCES "PUBLIC"."QUESTION"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."STUDENT" ADD CONSTRAINT "PUBLIC"."FK6NLAWTWHCNM4C6WUT05OBPB8T" FOREIGN KEY("ID_USER") REFERENCES "PUBLIC"."PERSON"("ID_USER") NOCHECK;   
ALTER TABLE "PUBLIC"."GROUPE_EVENT" ADD CONSTRAINT "PUBLIC"."FKHHAYXGLPVW12423VX8F1TXKQA" FOREIGN KEY("GROUPE_ID") REFERENCES "PUBLIC"."GROUPE"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."GROUPE_STUDENT" ADD CONSTRAINT "PUBLIC"."FK5FT7B6KME58WT3BOH4ECT6FNV" FOREIGN KEY("STUDENT_ID") REFERENCES "PUBLIC"."STUDENT"("ID_USER") NOCHECK;        
ALTER TABLE "PUBLIC"."TUTORIAL" ADD CONSTRAINT "PUBLIC"."FK3TFRFITS7ED2IDHW7D1D3VH0N" FOREIGN KEY("ID") REFERENCES "PUBLIC"."LEARNING_EVENT"("ID") NOCHECK;    
ALTER TABLE "PUBLIC"."TEACHER" ADD CONSTRAINT "PUBLIC"."FK1XIKJO49S2B0PT45RXUVD1AXT" FOREIGN KEY("ID_USER") REFERENCES "PUBLIC"."PERSON"("ID_USER") NOCHECK;   
ALTER TABLE "PUBLIC"."LEARNING_EVENT" ADD CONSTRAINT "PUBLIC"."FK1SY57CP8JX9XP7C2XGA1FOT4L" FOREIGN KEY("TEACHER_ID") REFERENCES "PUBLIC"."TEACHER"("ID_USER") NOCHECK;        
ALTER TABLE "PUBLIC"."GROUPE" ADD CONSTRAINT "PUBLIC"."FKO3D77T1QNVFIKOEOW2YCP0L5I" FOREIGN KEY("OWNER_ID") REFERENCES "PUBLIC"."TEACHER"("ID_USER") NOCHECK;  
ALTER TABLE "PUBLIC"."GROUPE_STUDENT" ADD CONSTRAINT "PUBLIC"."FK5WMW3SQEU6NHJU8WDPJPQRI7A" FOREIGN KEY("GROUPE_ID") REFERENCES "PUBLIC"."GROUPE"("ID") NOCHECK;               
ALTER TABLE "PUBLIC"."SUBJECT" ADD CONSTRAINT "PUBLIC"."FK33W7AIGIWM8R31IUGDVBGECM7" FOREIGN KEY("FIELD_ID") REFERENCES "PUBLIC"."FIELD"("ID") NOCHECK;        
ALTER TABLE "PUBLIC"."USER_INFO" ADD CONSTRAINT "PUBLIC"."FK9CRS2QP3HFKM140KEX944JLET" FOREIGN KEY("ID_USER") REFERENCES "PUBLIC"."PERSON"("ID_USER") NOCHECK; 
ALTER TABLE "PUBLIC"."GROUPE_EVENT" ADD CONSTRAINT "PUBLIC"."FKIEO3MFBWR4WCOV5BV11JQSEQR" FOREIGN KEY("EVENT_ID") REFERENCES "PUBLIC"."LEARNING_EVENT"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."QUESTION" ADD CONSTRAINT "PUBLIC"."FK49CRTL3LBARPRQH9D3W10OJOW" FOREIGN KEY("QUESTIONNNARY_ID") REFERENCES "PUBLIC"."QUESTIONNARY"("ID") NOCHECK;        
ALTER TABLE "PUBLIC"."COMMENT" ADD CONSTRAINT "PUBLIC"."FKJY4M3PLKOPIJ1M8B1O9H3LRE0" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."PERSON"("ID_USER") NOCHECK;   
ALTER TABLE "PUBLIC"."LEARNING_EVENT" ADD CONSTRAINT "PUBLIC"."FK1GQUOA7SYEKHR2WJ516IATROW" FOREIGN KEY("SUBJECT_ID") REFERENCES "PUBLIC"."SUBJECT"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."COMMENT" ADD CONSTRAINT "PUBLIC"."FKFVWM0MY5SLXXLHQQGY94LGXI1" FOREIGN KEY("PARENT_ID") REFERENCES "PUBLIC"."LEARNING_EVENT"("ID") NOCHECK;              
